@url = http://localhost:3000/api/user/

GET {{url}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYjU0YjA3NmRjNDNmMzBhYzJjZDFmNSIsImlhdCI6MTYwNTczNjc3NCwiZXhwIjoxNjA1ODIzMTc0fQ.Zr9rY_jNm4y6Hb2AewwCIgzosqvwZVfSnzuP-Gq0U-8
###
POST {{url}}
Content-Type: application/json

{
  "name":"Fernando",
  "email": "fernando3@gmail.com",
  "password": 123456
}

###
GET {{url}}5fb2eedd6403a347c0f5d4d8

###
DELETE {{url}}5fb54a9d9316a33360bd3014

###
PATCH {{url}}5fb30557d858a64194d98490
Content-Type: application/json

{
  "name": "Abelardino",
  "email": "abelfubu@gmail.com",
  "password": "1456"
}