@url = http://localhost:3000/api/users

GET {{url}}?from=0&pageSize=0
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYjMwNTU3ZDg1OGE2NDE5NGQ5ODQ5MCIsImlhdCI6MTYwNTkwMTgyNiwiZXhwIjoxNjA1OTg4MjI2fQ.AsTiJ4k4RFrAKsUh7WJugBNY8_CNy-MhkIuc_Efxv4s
###
POST {{url}}
Content-Type: application/json

{
  "name":"test15",
  "email": "test15@gmail.com",
  "password": 123456
}

###
GET {{url}}5fb2eedd6403a347c0f5d4d8

###
DELETE {{url}}/5fb3f3c99e12af09b0069678
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYjMwNTU3ZDg1OGE2NDE5NGQ5ODQ5MCIsImlhdCI6MTYwNTkwMTgyNiwiZXhwIjoxNjA1OTg4MjI2fQ.AsTiJ4k4RFrAKsUh7WJugBNY8_CNy-MhkIuc_Efxv4s

###
PATCH {{url}}5fb30557d858a64194d98490
Content-Type: application/json

{
  "name": "test1",
  "email": "test1@gmail.com",
  "password": "123456"
}